### ISSUE TITLE
Getting this Error on Example 5, "$win32_compiler -o pwn.exe avet.c" command

### ISSUE THREAD

**Issue by mgraf2** [govolution/avet#5]
![image](https://cloud.githubusercontent.com/assets/24736547/24462925/e253fa12-146a-11e7-84ec-414582a4e40f.png)

**Comment by govolution** [comment]
Thx! Did a quick fix, should work now.

**Comment by mgraf2** [comment]
Still getting same issue with latest.
![image](https://cloud.githubusercontent.com/assets/24736547/24478741/a2a5740e-14a1-11e7-879f-27e62909e246.png)

**Comment by govolution** [comment]
Sorry for that, forgot to update the README.md. 
You can also call
./build/build_win32_meterpreter_rev_https_shikata_load_ie.sh
from your avet directory.
